# Generated by Django 4.0.6 on 2024-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='00:00', max_length=100),
        ),
    ]
