# Generated by Django 4.0.6 on 2024-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_rename_nome_album_titulo_rename_nome_musica_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(default='letra não disponível'),
        ),
    ]
