# Generated by Django 4.0.6 on 2024-06-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoLEI', '0002_remove_disciplina_curriculariunitreadablecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='apresentacao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='competencias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(to='cursoLEI.disciplina'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='objetivos',
            field=models.TextField(),
        ),
    ]
