# Generated by Django 4.0.6 on 2024-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoLEI', '0003_alter_curso_apresentacao_alter_curso_competencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='conteudos',
            field=models.CharField(default='Conteúdos Programáticos Padrão', max_length=500, verbose_name='conteudos'),
        ),
    ]
