# Generated by Django 4.0.6 on 2024-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoLEI', '0004_alter_disciplina_code_alter_disciplina_conteudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_cientifica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='conteudos',
            field=models.CharField(default='Conteúdos Programáticos Padrão', max_length=500),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docente',
            name='disciplina',
            field=models.ManyToManyField(to='cursoLEI.disciplina'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linguagem_programacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='conceitos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='gitLink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagens',
            field=models.ManyToManyField(to='cursoLEI.linguagem_programacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
