# Generated by Django 4.0.6 on 2024-03-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('ArtigoID', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=255)),
                ('Conteudo', models.TextField()),
                ('DataPublicacao', models.DateTimeField(auto_now_add=True)),
                ('Visivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('AutorID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('DataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('RatingID', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('DataRating', models.DateTimeField(auto_now_add=True)),
                ('ArtigoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artigos.artigos')),
                ('AutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artigos.autores')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('ComentarioID', models.AutoField(primary_key=True, serialize=False)),
                ('Comentario', models.TextField()),
                ('DataComentario', models.DateTimeField(auto_now_add=True)),
                ('ArtigoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artigos.artigos')),
                ('AutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artigos.autores')),
            ],
        ),
        migrations.AddField(
            model_name='artigos',
            name='AutorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artigos.autores'),
        ),
    ]
