# Generated by Django 4.0.6 on 2024-03-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigos',
            new_name='Artigo',
        ),
        migrations.RenameModel(
            old_name='Autores',
            new_name='Autor',
        ),
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
