# Generated by Django 4.0.6 on 2024-03-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0002_rename_artigos_artigo_rename_autores_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='ArtigoID',
            new_name='artigo_id',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='AutorID',
            new_name='autor_id',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='Conteudo',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='DataPublicacao',
            new_name='data_publicacao',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='Visivel',
            new_name='visivel',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='AutorID',
            new_name='autor_id',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='DataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ArtigoID',
            new_name='artigo_id',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='AutorID',
            new_name='autor_id',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='Comentario',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ComentarioID',
            new_name='comentario_id',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='DataComentario',
            new_name='data_comentario',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ArtigoID',
            new_name='artigo_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='AutorID',
            new_name='autor_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='DataRating',
            new_name='data_rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='RatingID',
            new_name='rating_id',
        ),
    ]
